### ISSUE TITLE
Not possible to enter the view data table in an embedded sheet with keyboard shortcuts

### ISSUE THREAD

**Issue by mlb76** [qlik-oss/sn-table#294]
Not possible to enter the view data table in an embedded sheet with keyboard shortcuts, so that you can move between columns and rows in the table.

**Comment by haxxmaxx** [comment]
Well, that depends on a setting. The mashups we have setup so far does not have the setting turning on, treating the chart as a sheet object. When that is off, you should always be able to tab into the table. I'll add a low prio tag since it most likely works, but not prioritized to have the mashup working perfectly
